app/bps/cms/models.py
"""
    models.py: auth bp db models
"""
from datetime import datetime

# import database session
from app.extensions import db


class DateTimeMixin(
    object
):  # pylint: disable=useless-object-inheritance,too-few-public-methods
    """
    timestamp class
    """

    created_on = db.Column(db.DateTime, default=datetime.now)
    updated_on = db.Column(db.DateTime, default=datetime.now, onupdate=datetime.now)


class Post(
    DateTimeMixin, db.Model
):  # pylint: disable=useless-object-inheritance,too-few-public-methods
    """
    post class
    """

    __tablename__ = "posts"
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(255))
    slug = db.Column(db.String(255))
    content = db.Column(db.Text)
    tags = db.Column(db.String(255))
    image_filename = db.Column(db.String, default=None, nullable=True)
    image_url = db.Column(db.String, default=None, nullable=True)
    published = db.Column(db.Boolean, default=False)
    published_on = db.Column(db.DateTime, nullable=True)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))

    def __repr__(self):
        """
        post string representation method
        """
        return "<Post {}>".format(self.slug)

app/bps/cms/__init__.py
"""
    __init__.py: cms module
"""

app/bps/cms/controllers.py
"""
    controller.py: contains all handlers for cms bp
"""
# import os to remove files
import os

# flask dependencies
from flask import (
    Blueprint,
    request,
    render_template,
    flash,
    redirect,
    url_for,
    current_app,
    abort,
)

# import login manager
from flask_login import login_required

# import slug creation libs
from slugify import slugify

# import post model
from app.bps.cms.models import Post

# import db session
from app.extensions import db, uploads

# blueprint
cms = Blueprint("cms", __name__, url_prefix="/cms")


@cms.route("/", methods=["GET"])
@login_required
def home():
    """
    cms dashboard page
    """
    # sort stories by creation date
    stories = Post.query.all()[::-1]
    # get tags
    tags = list({post.tags for post in stories})
    # render cms page
    return render_template(
        "cms.html",
        tags=tags,
        stories=stories,
        app_name=current_app.config["APP_NAME"],
    )


@cms.route("/editor", methods=["GET"])
@login_required
def editor():
    """
    editor page
    """
    # render summernote editor page
    return render_template("editor.html")


@cms.route("/upload", methods=["POST"])
@login_required
def upload():
    """
    upload image
    """
    # image upload url doesn't render anything
    try:
        # try saving image and return url on disk
        image_filename = uploads.save(request.files["image"])
        image_url = uploads.url(image_filename)
        # return image url
        return image_url
    except Exception as error:  # pylint: disable=broad-except
        # log
        current_app.logger.warning("upload failed with: %s" % str(error))
        # if image can't be saved returned empty string as url
        return ""


@cms.route("/save", methods=["POST"])
@login_required
def save():  # pylint: disable=inconsistent-return-statements
    """
    save post
    """
    if request.method == "POST":
        try:
            # get post data from form
            title = request.form["title"]
            slug = slugify(title)
            content = request.form["content"]
            tags = request.form["tags"]
        except Exception as error:  # pylint: disable=broad-except
            # log
            current_app.logger.warning("form data failed with: %s" % str(error))
            # return error page
            abort(500)
        # try and get main image if not just keep it empty
        try:
            image_filename = uploads.save(request.files["image"])
            image_url = uploads.url(image_filename)
        except Exception as error:  # pylint: disable=broad-except
            # log
            current_app.logger.warning("file data failed with: %s" % str(error))
            # set to empty
            image_filename = ""
            image_url = ""
        try:
            # check if post already exists if so update
            if Post.query.filter_by(slug=slug).first():
                post = Post.query.filter_by(slug=slug).first()
                post.title = title
                post.slug = slug
                post.content = content
                post.tags = tags
                post.image_filename = image_filename
                post.image_url = image_url
            else:
                # create post
                post = Post(
                    title=title,
                    slug=slug,
                    content=content,
                    tags=tags,
                    image_filename=image_filename,
                    image_url=image_url,
                )
                # add to database
                db.session.add(post)
            # commit the changes
            db.session.commit()
            db.session.close()
        except Exception as error:  # pylint: disable=broad-except
            # log
            current_app.logger.warning("post create failed with: %s" % str(error))
            # return error page
            abort(500)
        # alert user
        flash("saved.")
        # redirect to cms homepage
        return redirect(url_for("cms.home"))


@cms.route("/edit/<string:slug>", methods=["GET", "POST"])
@login_required
def edit(slug):
    """
    edit post
    """
    # edit specific story
    story = Post.query.filter_by(slug=slug).first()
    # render edit page
    return render_template("edit.html", story=story)


@cms.route("/publish/<string:slug>", methods=["POST"])
@login_required
def publish(slug):
    """
    publish post
    """
    # get post by id
    post = Post.query.filter_by(slug=slug).first()
    # set published to True
    post.published = True
    # commit changes to database
    db.session.commit()
    db.session.close()
    # alert user
    flash("published.")
    return redirect(url_for("cms.home"))


@cms.route("/unpublish/<string:slug>", methods=["POST"])
@login_required
def unpublish(slug):
    """
    unpublish post
    """
    # get post by id
    post = Post.query.filter_by(slug=slug).first()
    # set published to false
    post.published = False
    # commit changes to database
    db.session.commit()
    db.session.close()
    # alert
    flash("unpublished.")
    # redirect
    return redirect(url_for("cms.home"))


@cms.route("/delete/<string:slug>", methods=["POST"])
@login_required
def delete(slug):
    """
    delete post
    """
    # need to add ways to depelete post images
    post = Post.query.filter_by(slug=slug).first()
    post_image_path = os.path.join(
        os.getcwd(), "app/static/images/uploads", post.image_filename
    )
    # if path exists
    if post_image_path:
        # delete the image associated with the post stored on disk
        os.remove(post_image_path)
    # delete post
    db.session.delete(post)
    db.session.commit()
    db.session.close()
    # alert user
    flash("deleted")
    # redirect to cms
    return redirect(url_for("cms.home"))

app/mod_auth/controllers.py
# flask
from flask import (
    Blueprint,
    request,
    render_template,
    flash,
    session,
    redirect,
    url_for,
    abort,
    current_app,
)
# url parsing
from urllib.parse import urlparse

# auth
from flask_login import current_user, login_user, logout_user

# db model
from app.mod_auth.models import User

# db extension
from app.extensions import db

# send mail functions
from app.mail import send_mail
from app.extensions import mail

# import serializer
from app import ts


# auth module
mod_auth = Blueprint("auth", __name__, url_prefix="/")

# Set the route and accepted methods
@mod_auth.route("/signin", methods=["GET", "POST"])
def signin():
    if request.method == "POST":
        try:
            # get form values
            email = request.form["email"]
            password = request.form["password"]
        except Exception as e:
                # log
                current_app.logger.warning("form data failed.")
                # return error page
                abort(500)
        try:
            # find user
            user = User.query.filter_by(email=email).first()
            # check user has been found
            if user is None or not user.check_password(password):
                flash("invalid credentials.")
                return redirect(url_for("auth.signin"))
        except Exception as e:
                # log
                current_app.logger.warning("exists validation failed.")
                # return error page
                abort(500)
        try:
            # login user if found
            login_user(user)
            # get next from argument
            next_page = request.args.get("next")
            if not next_page or urlparse(next_page).netloc != "" or next_page == "/":
                next_page = url_for("cms.editor")
        except Exception as e:
            # log
            current_app.logger.warning("login user failed.")
            # return error page
            abort(500)
        # alert user
        flash("signed in.")
        # return response
        return redirect(next_page)
    # return sign in page
    return render_template("signin.html")


@mod_auth.route("/signup", methods=["GET", "POST"])
def signup():
    if current_app.config["MAX_USERS_NOT_REACHED"]:
        if request.method == "POST":
            try:
                # get data from forms
                email = request.form["email"]
                password = request.form["password"]
            except Exception as e:
                # log
                current_app.logger.warning("form data failed.")
                # return error page
                abort(500)
            try:
                # find user
                user = User.query.filter_by(email=email).first()
                # check email has been found
                if user != None:
                    # return to sign up page
                    return redirect(url_for("auth.signup"))
            except Exception as e:
                # log
                current_app.logger.warning("exists validation failed.")
                # return error page
                abort(500)
            try:
                # initialize user
                user = User(email=email, password=password)
                # add to session
                db.session.add(user)
                db.session.commit()
                db.session.close()
            except Exception as e:
                # log
                current_app.logger.warning("user init failed.")
                # return error page
                abort(500)
            try:
                # prepare email
                subject = "confirm account."
                # generate token
                token = ts.dumps(email, salt="email-confirm-key")
                # build recover url
                confirm_url = url_for("auth.confirm_email", token=token, _external=True)
                # send the emails
                send_mail(
                    subject, current_app.config["MAIL_USERNAME"], [email], confirm_url
                )
                # update user count
                current_app.config["MAX_USERS_NOT_REACHED"] = False
            except Exception as e:
                # log
                current_app.logger.warning("form data failed.")
                # return error page
                abort(500)
            # update user
            flash("account created. confirm email address.")
            # return to login
            return redirect(url_for("auth.signin"))
        # render signup page
        return render_template("signup.html")
    # sign up not active
    flash("signup not active.")
    return redirect(url_for("signin"))


@mod_auth.route("/confirm/<token>", methods=["GET", "POST"])
def confirm_email(token):
    # check validity of token passed using the serializer
    try:
        email = ts.loads(token, salt="email-confirm-key", max_age=86400)
    except:
        abort(400)
    try:
        # get the user using the email
        user = User.query.filter_by(email=email).first_or_404()
        # confirm user
        user.confirmed = True
        # save changes in database
        db.session.commit()
        db.session.close()
        # alert user
        flash("email address confirmed.")
        return redirect(url_for("auth.signin"))
    except:
        # log
        current_app.logger.warning("confirm failed.")
        # return error page
        abort(500)


@mod_auth.route("/reset", methods=["GET", "POST"])
def request_reset():
    if request.method == "POST":
        try:
            # get email from form
            email = request.form["email"]
        except Exception as e:
            # log
            current_app.logger.warning("form data failed.")
            # return error page
            abort(500)
        try:
            # query user by emeail
            user = User.query.filter_by(email=email).first()
            # check if user has been found
            if user is None:
                flash("invalid credentials.")
                # return to reset page
                return render_template("request_reset.html")
        except Exception as e:
                # log
                current_app.logger.warning("exists validation failed.")
                # return error page
                abort(500)
        try:
            # prepare email
            subject = "password reset requested"
            # generate token
            token = ts.dumps(user.email, salt="recover-key")
            # build recover url
            recover_url = url_for("auth.reset_with_token", token=token, _external=True)
            # send the email
            send_mail(subject, current_app.config["MAIL_USERNAME"], [email], recover_url)
        except Exception as e:
            # log
            current_app.logger.warning("send reset failed.")
            # return error page
            abort(500)
        # alert user
        flash("reset link sent.")
        return redirect(url_for("base.home"))
    flash("reset password.")
    return render_template("request_reset.html")


@mod_auth.route("/reset/<token>", methods=["GET", "POST"])
def reset_with_token(token):
    # check validity of token passed using the serializer
    try:
        email = ts.loads(token, salt="recover-key", max_age=86400)
    except:
        abort(400)
    # change password if valid token provided
    if request.method == "POST":
        try:
            # get new password from form
            password = request.form["password"]
        except Exception as e:
            # log
            current_app.logger.warning("form data failed.")
            # return error page
            abort(500)
        try:
            # get user using email
            user = User.query.filter_by(email=email).first_or_404()
            # set hashed password in database
            user.set_password(password)
            # save changes in database
            db.session.commit()
            db.session.close()
        except Exception as e:
                # log
                current_app.logger.warning("password reset failed.")
                # return error page
                abort(500)
        # alert user
        flash("password successfully reset.")
        return redirect(url_for("auth.signin"))
    return render_template("reset_with_token.html", token=token)


@mod_auth.route("/signout")
def signout():
    logout_user()
    flash("signed out.")
    return redirect(url_for("base.home"))

app/templates/cms.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="description" content="teret stories page" />
  <meta name="author" content="Abenezer Mamo" />
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>cms</title>
  <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" />

  <!-- Stylesheet -->
  <link href="{{ url_for('static', filename='css/gallery-materialize.min.css') }}" rel="stylesheet" />

  <link href="{{ url_for('static', filename='css/base.css') }}" rel="stylesheet" />

  <!-- Material Icons -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />

  <link rel="stylesheet" type="text/css"
    href="http://cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/codemirror.min.css" />
  <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/theme/blackboard.min.css">
</head>

<body class="blog">
  <!-- nav -->
  <nav class="nav-extended">
    <div class="nav-background">
      <div class="pattern active"></div>
    </div>
    <div class="nav-wrapper container">
      <a href="#" data-target="nav-mobile" class="sidenav-trigger black-text"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <li>
          <a class="link" href="{{ url_for('cms.editor') }}">EDITOR</a>
        </li>
        <li>
          <a class="link" href="{{ url_for('auth.signout') }}">SIGN OUT</a>
        </li>
      </ul>
      <div id="snackbar">
        {% with messages = get_flashed_messages() %} {% if messages %} {% for
          message in messages %} {{ message }} {% endfor %} {% endif %} {%
          endwith %}
      </div>
      <div class="nav-header center white">
        <span class="header-title">
          <h1>{{ app_name }}</h1>
        </span>
      </div>
    </div>

    <!-- tags -->
    <div class="categories-wrapper white darken-1">
      <div class="categories-container">
        <ul class="categories container">
          <li class="active description">
            <a class="black-text tag-title" href="#all">All</a>
          </li>
          {% for tag in tags %}
          <li>
            <a class="tag-title black-text" href="#{{ tag.lower() }}">{{ tag.lower() }}</a>
          </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </nav>
  <!-- side nav-->
  <ul class="sidenav" id="nav-mobile">
    <li><a href="{{ url_for('cms.editor') }}">EDITOR</a></li>
    <li><a href="{{ url_for('auth.signout') }}">SIGN OUT</a></li>
  </ul>
  <!-- content -->
  <div id="portfolio" class="section gray">
    <div class="container">
      <div class="gallery row">
        {% for story in stories %}
        <div class="col l4 m6 s12 gallery-item gallery-expand gallery-filter {{ story.tags.lower() }}">
          <div class="gallery-curve-wrapper">
            <div class="gallery-header">
              <div class="container">
                <div class="row">
                  <span class="card-tag">{{ story.tags }}</span>
                </div>
              </div>
              <div class="container">
                <div class="row">
                  <span class="card-title">{{ story.title }}</span>
                </div>
              </div>
              <div class="container">
                <div class="row">
                  <span class="card-time"><i class="tiny material-icons">create</i>{{ story.created_on
                    | format_datetime("short") }}</span>
                </div>
                <div class="row">
                  {% if story.published %}
                  <span class="card-time"><i class="tiny material-icons">album</i>{{
                        story.published_on | format_datetime("short") }}</span>
                  {% endif %}
                </div>
              </div>
            </div>
            <div class="gallery-body">
              <div class="title-wrapper">
                <div class="container">
                  <div class="row">
                    <span class="card-tag">{{ story.tags }}</span>
                    <span class="card-time"><i class="tiny material-icons">create</i>{{ story.created_on
                      | format_datetime("short") }}</span>
                    {% if story.published %}
                    <span class="card-time"> <i class="tiny material-icons">album</i> {{
                        story.published_on | format_datetime("short") }}</span>
                    {% endif %}

                  </div>
                </div>
                <div class="container">
                  <div class="row">
                    <span class="card-title">{{ story.title }}</span>
                  </div>
                </div>
              </div>
              <div class="container">
                <div class="row">
                  <p class="description content">
                    {{ story.content | safe }}
                  </p>
                </div>
                <div class="row">
                  <div class="col s12 m12 l3">
                    <form action="{{ url_for('cms.edit', slug = story.slug) }}" method="POST">
                      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                      <button class="btn-floating btn-small waves-effect waves-light blue" value="submit" type="submit"
                        name="submit">
                        <i class="material-icons">mode_edit</i>
                      </button>
                    </form>
                  </div>
                  <div class="col s12 m12 l3">
                    <form action="{{ url_for('cms.delete', slug = story.slug) }}" method="POST">
                      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                      <button class="btn-floating btn-small waves-effect waves-light red" value="submit" type="submit"
                        name="submit">
                        <i class="material-icons">delete</i>
                      </button>
                    </form>
                  </div>
                  <div class="col s12 m12 l3">
                    <form action="{{ url_for('cms.publish', slug = story.slug) }}" method="POST">
                      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                      <button class="btn-floating btn-small waves-effect waves-light green" value="submit" type="submit"
                        name="submit">
                        <i class="material-icons">vertical_align_top</i>
                      </button>
                    </form>
                  </div>
                  <div class="col s12 m12 l3">
                    <form action="{{ url_for('cms.unpublish', slug = story.slug) }}" method="POST">
                      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                      <button class="btn-floating btn-small waves-effect waves-light yellow" value="submit"
                        type="submit" name="submit">
                        <i class="material-icons">vertical_align_bottom</i>
                      </button>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
  <!-- javascript -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <script src="{{ url_for('static', filename='js/imagesloaded.pkgd.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/masonry.pkgd.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/materialize.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/color-thief.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/galleryExpand.js') }}"></script>
  <script src="{{ url_for('static', filename='js/init.js') }}"></script>
  <script src="{{ url_for('static', filename='js/jquery-3.4.1.min.js') }}"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/codemirror.js"></script>
  <script src="http://cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/mode/xml/xml.min.js"></script>
  <script src="http://cdnjs.cloudflare.com/ajax/libs/codemirror/2.36.0/formatting.min.js"></script>
  <!-- alert -->
  <script>
    // get snackbar
    var snackbar = document.getElementById("snackbar");
    // get message
    var snackbar_message = snackbar.textContent;
    // check if message found
    if (/\S/.test(snackbar_message)) {
      // run materialize toast
      M.toast({ html: snackbar_message, classes: "rounded" });
      // remove message
      snackbar.innerHTML = "";
    }
  </script>
  <script>
    $('pre').each(function () {

      var $this = $(this),
        $code = $this.html(),
        $unescaped = $('<div/>').html($code).text();

      $this.empty();

      CodeMirror(this, {
        value: $unescaped,
        mode: 'javascript',
        lineNumbers: !$this.is('.inline'),
        readOnly: true
      });

    });
  </script>
</body>

</html>

app/templates/edit.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="description" content="teret stories page" />
  <meta name="author" content="Abenezer Mamo" />
  <title> editor </title>
  <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" />
  <meta name="csrf-token" content="{{ csrf_token() }}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/3.4.1/paper/bootstrap.min.css"
    crossorigin="anonymous">
  <link rel="stylesheet" type="text/css"
    href="http://cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/codemirror.min.css" />
  <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/theme/blackboard.min.css">
  <link href="{{ url_for('static', filename='summernote/summernote.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='css/editor.css') }}" rel="stylesheet">
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;700&display=swap');
  </style>
</head>

<body>
  <div class="container">
    <form method="post" action="{{ url_for('cms.save') }}" enctype=multipart/form-data>
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
      <div class="form-group">
        <label for="title">title</label>
        <input id="title" name="title" type="text" class="form-control" value="{{ story.title }}">
      </div>
      <div class="form-group">
        <label for="title">tags</label>
        <input id="tags" name="tags" type="text" class="form-control" value="{{ story.tags }}">
      </div>
      <div class="form-group">
        <label for="title">image</label>
        <input type="file" name="image" placeholder="file" class="form-control" />
      </div>
      <textarea id="summernote" name="content">{{ story.content }}</textarea>
      <div class="row submit-container">
        <button class="submit-buttom" type="submit" name="action">SAVE</button>
      </div>
    </form>
  </div>
  <script src="{{ url_for('static', filename='js/jquery-3.4.1.min.js') }}"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/codemirror.js"></script>
  <script src="http://cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/mode/xml/xml.min.js"></script>
  <script src="http://cdnjs.cloudflare.com/ajax/libs/codemirror/2.36.0/formatting.min.js"></script>
  <script src="{{ url_for('static', filename='summernote/summernote.js') }}"></script>
  <script>
    var csrftoken = $('meta[name=csrf-token]').attr('content')
    $.ajaxSetup({
      beforeSend: function (xhr, settings) {
        if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type)) {
          xhr.setRequestHeader("X-CSRFToken", csrftoken)
        }
      }
    })
  </script>
  <script>
    $('#summernote').summernote({
      height: ($(window).height() - 300),
      fontNames: ["Poppins", "Source Code Pro"],
      fontNamesIgnoreCheck: ["Poppins", "Source Code Pro"],
      fontSizes: ['8', '9', '10', '11', '12', '16', '18', '24', '36', '48', '64', '82', '150'],
      tabsize: 2,
      codemirror: {
        theme: 'blackboard'
      },
      toolbar: [
        // [groupName, [list of button]]
        ['cmds', ['undo', 'redo', 'clear']],
        ['style', ['style']],
        ['font', ['strikethrough', 'superscript', 'subscript']],
        ['fontsize', ['fontsize']],
        ['fontname', ['fontname']],
        ['color', ['color']],
        ['para', ['ul', 'ol', 'paragraph']],
        ['height', ['height']],
        ['table', ['table']],
        ['insert', ['link', 'picture', 'video']],
        ['view', ['fullscreen', 'codeview', 'help']],
        ['codemirror', ['codemirror']]
      ],
      callbacks: {
        onInit: function () {
          $('.summernote').summernote('codeview.activate');
        },
        onImageUpload: function (image) {
          uploadImage(image[0]);
        }
      }
    });

    function uploadImage(image) {
      var data = new FormData();
      data.append("image", image);
      $.ajax({
        url: "{{ url_for('cms.upload') }}",
        cache: false,
        contentType: false,
        processData: false,
        data: data,
        type: "post",
        success: function (url) {
          var image = $('<img>').attr('src', url);
          $('#summernote').summernote("insertNode", image[0]);
        },
        error: function (data) {
          console.log(data);
        }
      });
    }   
  </script>
</body>

</html>

app/templates/error.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="description" content="teret stories page" />
  <meta name="author" content="Abenezer Mamo" />
  <title>error</title>
  <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" />
  <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" />
  <link href="http://fonts.googleapis.com/css?family=Lato:300,400,700" rel="stylesheet" type="text/css" />
  <link rel="stylesheet" href="{{ url_for('static', filename='css/gallery-materialize.min.css') }}" />
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
  <script src="https://kit.fontawesome.com/d11a9ce67f.js"></script>
</head>

<body>
  <header>
    <section class="header-content valign-wrapper">
      <div class="container">
        <span class="header-title">
          <h1>{{ status_code }}</h1>
        </span>
        <p class="sub-text">{{ message }}</p>
      </div>
    </section>
  </header>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</body>

</html>